# Welcome to Jekyll!
#

# Site settings
title: I'm Joannas
description: |
  Here's where we get to know each other.
owner: Joannas Yeow # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: joannas.y@live.com.sg
baseurl: "" # the subpath of your site, e.g. /blog
url: "mailto:joannas.y@live.com.sg" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/joannasss
  github: https://github.com/joannasys
  linkedin-square: https://linkedin.com/in/joannasyeow
  facebook-official: https://facebook.com/yeowjoannas
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/joannasss/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
